{
 "title": "Sonarqube - Scan dashboard",
 "description": "The dashboard presents all metrics in detail and is meant for finer-grained analytics.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project_key", "label": "Project", "query": { "query": "label_values(project_key)" } }
  ]
 },
 "panels": [
  { "title": "Quality gates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quality Gate Status",
   "type": "stat",
   "description": "The state of the quality gate associated with your project. Possible values are ERROR and OK",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alert_status{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Lines of code",
   "type": "stat",
   "description": "- Lines (lines): The number of physical lines \n- Lines of code (ncloc): The number of physical lines that contain at least one character\n- Comment lines (comment_lines): The number of lines containing comment",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lines{project_key=\"$project_key\"}",
     "legendFormat": "Total lines "
    },
    {
     "expr": "comment_lines{project_key=\"$project_key\"}",
     "legendFormat": "Commented lines"
    },
    {
     "expr": "ncloc{project_key=\"$project_key\"}",
     "legendFormat": "Non-commented/non-empty lines"
    }
   ]
  },
  {
   "title": "The comment lines density",
   "type": "gauge",
   "description": "The comment lines density = comment lines / (lines of code + comment lines) * 100",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comment_lines_density{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of classes ",
   "type": "timeseries",
   "description": "The number of classes (including nested classes, interfaces, enums, and annotations).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "classes{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of statements",
   "type": "stat",
   "description": "The number of statements.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statements{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of functions",
   "type": "stat",
   "description": "The number of functions. Depending on the language, a function is defined as either a function, a method, or a paragraph.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "functions{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of files",
   "type": "stat",
   "description": "The number of files.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "files{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total of Issues",
   "type": "stat",
   "description": "The total count of issues in all states.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "violations{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Violations",
   "type": "piechart",
   "description": "The total count of issues of the specified severity, where xxx is one of: blocker, critical, major, minor, info.",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocker_violations{project_key=\"$project_key\"}",
     "legendFormat": "Blocker violations"
    },
    {
     "expr": "critical_violations{project_key=\"$project_key\"}",
     "legendFormat": "Critical violations"
    },
    {
     "expr": "info_violations{project_key=\"$project_key\"}",
     "legendFormat": "Info violations"
    },
    {
     "expr": "major_violations{project_key=\"$project_key\"}",
     "legendFormat": "Major violations"
    },
    {
     "expr": "minor_violations{project_key=\"$project_key\"}",
     "legendFormat": "Minor violations"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "piechart",
   "description": "The total count of issues in the state.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_issues{project_key=\"$project_key\"}",
     "legendFormat": "Open issues"
    },
    {
     "expr": "reopened_issues{project_key=\"$project_key\"}",
     "legendFormat": "Reopened issues"
    },
    {
     "expr": "confirmed_issues{project_key=\"$project_key\"}",
     "legendFormat": "Confirmed issues"
    },
    {
     "expr": "false_positive_issues{project_key=\"$project_key\"}",
     "legendFormat": "False positive issues"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "The number of vulnerability issues.",
   "type": "stat",
   "description": "The number of vulnerability issues.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "new_vulnerabilities{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The effort to fix all vulnerability issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_remediation_effort{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of Security Hotspots",
   "type": "stat",
   "description": "The number of Security Hotspots",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_hotspots_reviewed_status{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "description": "Security Rating (security_rating)\n- A = 0 Vulnerabilities\n- B = at least 1 Minor Vulnerability\n- C = at least 1 Major Vulnerability\n- D = at least 1 Critical Vulnerability\n- E = at least 1 Blocker Vulnerability",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_rating{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Security review rating",
   "type": "stat",
   "description": "The security review rating is a letter grade based on the percentage of Reviewed Security Hotspots.\n- A = >= 80%\n- B = >= 70% and <80%\n- C = >= 50% and <70%\n- D = >= 30% and <50%\n- E = < 30%",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_review_rating{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Duplications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Duplicated lines",
   "type": "stat",
   "description": "- Duplicated lines (duplicated_lines): The number of lines involved in duplications.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicated_lines{project_key=\"$project_key\"}",
     "legendFormat": "Duplicated lines"
    }
   ]
  },
  {
   "title": "Duplicated files",
   "type": "stat",
   "description": "- Duplicated files (duplicated_files): The number of files involved in duplications.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicated_files{project_key=\"$project_key\"} ",
     "legendFormat": "Duplicated files"
    }
   ]
  },
  {
   "title": "Duplicated blocks",
   "type": "stat",
   "description": "- Duplicated blocks (duplicated_blocks): The number of blocks involved in duplications.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicated_blocks{project_key=\"$project_key\"}",
     "legendFormat": "Duplicated files"
    }
   ]
  },
  {
   "title": "Duplicated Lines (%)",
   "type": "gauge",
   "description": "Duplicated lines (%) (duplicated_lines_density): duplicated_lines / (lines of code) * 100",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicated_lines_density{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Coverage",
   "type": "gauge",
   "description": "Coverage = (CT + CF + LC)/(2*B + EL)\nwhere:\n- CT = conditions that have been evaluated to 'true' at least once\n- CF = conditions that have been evaluated to 'false' at least once\n- LC = covered lines = linestocover - uncovered_lines\n- B = total number of conditions\n- EL = total number of executable lines (lines_to_cover)\n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coverage{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of lines that are covered by unit test",
   "type": "stat",
   "description": "The number of lines of code that could be covered by unit tests (for example, blank lines or full comments lines are not considered as lines to cover).",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lines_to_cover{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of skipped tests",
   "type": "stat",
   "description": "The number of skipped tests.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skipped_tests{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "The total number of bug issues",
   "type": "stat",
   "description": "The total number of bug issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bugs{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "description": "- A = 0 Bugs\n- B = at least 1 Minor Bug\n- C = at least 1 Major Bug\n- D = at least 1 Critical Bug\n- E = at least 1 Blocker Bug",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reliability_rating{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The effort to fix all bug issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reliability_remediation_effort{project_key=\"$project_key\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Maintainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "The total count of code smell issues",
   "type": "stat",
   "description": "The total count of code smell issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "code_smells{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Maintainability Rating",
   "type": "gauge",
   "description": "Formerly the SQALE rating.) The rating given to your project related to the value of your technical debt ratio. The default maintainability rating grid is:\n\n- A=0-0.05, B=0.06-0.1, C=0.11-0.20, D=0.21-0.5, E=0.51-1",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqale_rating{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "stat",
   "description": "A measure of effort to fix all code smells. The measure is stored in minutes in the database. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqale_index{project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Complexity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Complexity / File",
   "type": "stat",
   "description": "Complexity / File",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_complexity{project_key=\"$project_key\"}",
     "legendFormat": "{{project_key}}"
    }
   ]
  },
  {
   "title": "Cognitive Complexity",
   "type": "stat",
   "description": "How hard it is to understand the code's control flow",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cognitive_complexity{project_key=\"$project_key\"}",
     "legendFormat": "{{project_key}}"
    }
   ]
  },
  {
   "title": "Cyclomatic Complexity",
   "type": "stat",
   "description": "Complexity refers to cyclomatic complexity, a quantitative metric used to calculate the number of paths through the code.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "complexity{project_key=\"$project_key\"}",
     "legendFormat": "{{project_key}}"
    }
   ]
  }
 ]
}